In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score

In [2]:
iris = load_iris()

In [3]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(iris.data,iris.target,test_size=0.3)

In [8]:
from sklearn.linear_model import LogisticRegression
cross_val_score(LogisticRegression(),iris.data,iris.target,cv=3)

C:\Users\admin\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.98, 0.96, 0.98])

In [9]:
from sklearn.svm import SVC
cross_val_score(SVC(),iris.data,iris.target,cv=3)

array([0.96, 0.98, 0.94])

In [10]:
from sklearn.ensemble import RandomForestClassifier
cross_val_score(RandomForestClassifier(),iris.data,iris.target,cv=3)

array([0.98, 0.94, 0.98])